/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.shapes;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Shapes {

    public static void main(String[] args) {
	    SpringApplication.run(Shapes.class, args);
    }
}
